server.port: 8888
spring:
    jpa.hibernate.ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/student_db
        username: root 
        password: mysql
        
security: 
  oauth2:
    client:
      clientId: 1529909617054369
      clientSecret: 86ccbe0715090e22554b19836dda2e40
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me